# Generated by Django 3.1.14 on 2022-11-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20221129_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemons',
            new_name='Pokemon',
        ),
    ]
