# Generated by Django 3.1.14 on 2022-12-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20221201_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Endurance',
            new_name='endurance',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Protection',
            new_name='protection',
        ),
    ]
